export const SCREENS = {
  home: 'home',
  cart: 'cart',
  favorites: 'favorites',
  profile: 'profile',
  trendyol: 'trendyol',
  productDetail: 'productDetail',
  productList: 'products',
  tab: 'tabNavigation',
  MainTabs: 'MainTabs',
  login: 'login',
  signup: 'signup',
  forgetPassword: 'forgetPassword',
  myAccount: 'myAccount',
  notification: 'notification',
};
